version: 1
script:
  - rm -rf AppDir | true
  - mkdir -p AppDir/usr/local/share
  - mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
  - sed -i 's/APP_MODE = "@MODE@"/APP_MODE = "appimage"/' nottodbox/scripts/consts.py
  - cp -r nottodbox AppDir/usr/local/share
  - cp share/icons/hicolor/scalable/apps/io.github.mukonqi.nottodbox.svg AppDir/usr/share/icons/hicolor/scalable/apps
  - cp LICENSE.txt README.md AppDir/usr/local/share/nottodbox
  - python3 .github/scripts/translations.py --appimage
  - pip install --ignore-installed --prefix=/usr --no-cache-dir --root=AppDir PySide6-Essentials
  

AppDir:
  path: ./AppDir

  app_info:
    id: io.github.mukonqi.nottodbox
    name: nottodbox
    icon: io.github.mukonqi.nottodbox
    version: v0.0.90
    exec: usr/bin/python3
    exec_args: "/usr/local/share/nottodbox/__init__.py"

  pacman:
    Architecture: x86_64
    include:
      - glib2
      - python
      - xcb-util-cursor
    exclude:
      - gcc-libs
    options:
      SigLevel: "Optional TrustAll"

  files:
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*

  runtime:
    env:
      PYTHONHOME: '${APPDIR}/usr'
      PYTHONPATH: '${APPDIR}/usr/lib/python3.13/site-packages'

AppImage:
  update-information: 'gh-releases-zsync|MuKonqi|nottodbox|latest|nottodbox-*x86_64.AppImage.zsync'
  sign-key: None
  arch: x86_64
