# Credit: While making this file <https://github.com/DavidoTek/ProtonUp-Qt/blob/main/AppImageBuilder.yml> helped me as a reference.

version: 1
script:
  - rm -rf AppDir | true
  - mkdir -p AppDir/usr/lib/python3.13/site-packages
  - mkdir -p AppDir/usr/share/icons
  - cp -r nottodbox AppDir/usr/lib/python3.13/site-packages
  - cp -r share/icons AppDir/usr/share/icons
  - cp LICENSE.txt AppDir/usr/lib/python3.13/site-packages/nottodbox
  - python3 po/merge.py
  - pip install --ignore-installed --prefix=/usr --no-cache-dir --root=AppDir PySide6-Essentials
  - rm -rf AppDir/usr/lib/python3.13/site-packages/PySide6/Qt/{qml,libexec,translations}
  - rm -f AppDir/usr/lib/python3.13/site-packages/PySide6/{assistant,designer,linguist,lrelease,lupdate}
  - rm -f AppDir/usr/lib/python3.13/site-packages/PySide6/{qml*,svgtoqml*,Qt3D*,QtBluetooth*,QtCharts*,QtConcurrent*,QtDataVisualization*,QtDBus*,QtDesigner*,QtGraphs*,QtHelp*,QtHttpServer*,QtLocation*,QtMultimedia*,QtNetwork*,QtNfc*,QtOpenGL*,QtPdf*,QtPositioning*,QtPrintSupport*,QtQml*,QtQuick*,QtRemoteObjects*,QtScxml*,QtSensors*,QtSerialBus*,QtSerialPort*,QtSpatialAudio*,QtSql*,QtStateMachine*,QtSvg*,QtTest*,QtTextToSpeech*,QtUiTools*,QtWeb*,QtXml*}
  - shopt -s extglob
  - rm -rf AppDir/usr/lib/python3.13/site-packages/PySide6/Qt/lib/!(libicudata*|libicuuc*|libicui18n*|libQt6DBus*|libQt6OpenGL*|libQt6XcbQpa*|libQt6Wayland*|libQt6Egl*|libQt6Core*|libQt6Gui*|libQt6Widgets*)

AppDir:
  path: ./AppDir

  app_info:
    id: io.github.mukonqi.nottodbox
    name: nottodbox
    icon: io.github.mukonqi.nottodbox
    version: v0.0.8-3
    exec: usr/bin/python3
    exec_args: "-m nottodbox $@"

  pacman:
    Architecture: x86_64
    include:
      - glib2
      - python
      - xcb-util-cursor
    options:
      SigLevel: "Optional TrustAll"

  files:
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*

  runtime:
    env:
      PYTHONHOME: '${APPDIR}/usr'
      PYTHONPATH: '${APPDIR}/usr/lib/python3.13/site-packages'

AppImage:
  update-information: 'gh-releases-zsync|MuKonqi|nottodbox|latest|nottodbox-*x86_64.AppImage.zsync'
  sign-key: None
  arch: x86_64
