name: Bug Report
description: Found a bug? Please help us improve by reporting it here.
title: "[BUG] "
labels: bug
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: log
    attributes:
      label: Log
      description: |
        Please copy-paste the content of a relevant log file.
        You can find logs in:

        - Linux: `~/.local/share/nottodbox/logs`
        - macOS: `~/Library/Application Support/nottodbox/logs`
        - Windows: `C:/Users/<USER>/AppData/Local/nottodbox/logs`
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide clear steps so we can reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Context like Screenshots
      description: Add any other information that might help us understand or reproduce the issue.