name: Feature Request
description: Suggest an idea for this project.
title: "[FEATURE] "
labels: enhancement
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the details below to help us understand your idea.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a brief summary of the feature.
      placeholder: A concise description of the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed. What problem does it solve or improve?
      placeholder: Describe the problem or use case
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Feature Details
      description: Describe how this feature should work. Include examples or possible implementation details.
      placeholder: Detailed explanation, usage examples, etc.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions? If yes, please describe them.
      placeholder: Alternative approaches or workarounds
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Add any other context, screenshots, or links that might help.
      placeholder: Any other relevant info
    validations:
      required: false