# Credit: While making this file <https://github.com/DavidoTek/ProtonUp-Qt/blob/main/AppImageBuilder.yml> helped me as a reference.

name: Build AppImage

on:
  push:
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Dependencies
      run: pacman -Sy --noconfirm appstream binutils coreutils desktop-file-utils fakeroot fuse2 gettext gdk-pixbuf2 patchelf python python-pip python-setuptools squashfs-tools strace util-linux zsync

    - name: Download AppImageBuilder
      run: pip3 install appimage-builder
    
    - name: Build AppImage
      run: appimage-builder --recipe .github/scripts/appimage.yml

    - name: Upload AppImage
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "appimage"
        prerelease: true
        title: "New AppImage Pre-release"
        files: ./nottodbox*.AppImage*