name: Build AppImage

on:
  workflow_dispatch:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install -y libfuse2 libglib2.0-0 libopengl0 libxcb-cursor0 libxcb-keysyms1 libxcb-icccm4 libxcb-shape0-dev libxkbcommon-x11-0 libxcb-xkb-dev patchelf wget
          pip install pyinstaller PySide6-essentials appimage-builder

      - name: Build executable
        run: bash .github/scripts/pyinstaller.sh

      - name: Build AppImage
        run: |
          appimage-builder --skip-test
          mv Nottodbox-x86_64.AppImage nottodbox.AppImage

      - name: Upload to stable release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.2.1
        with:
          body_path: "CHANGELOG.md"
          files: 'nottodbox.AppImage'

      - name: Upload to nightly release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: 'nottodbox.AppImage'
          tag_name: nightly
          prerelease: true