name: Build AppImage

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  delete-old-nightly-release:
    env:
      GH_TOKEN: ${{ github.token }}
    
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Delete old nightly release
      run: gh release delete nightly --cleanup-tag --yes | true

  build-appimage:
    runs-on: ubuntu-24.04
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Download dependencies
      run: pacman -Sy --noconfirm gettext python python-pip

    - name: Set translations
      run: python3 scripts/translations.py --appimage

    - name: Install PySide6
      run: pip install --ignore-installed --prefix=/usr --no-cache-dir --root=AppDir PySide6-Essentials
    
    - name: Build AppImage
      uses: AppImageCrafters/build-appimage-action@master
      env:
        UPDATE_INFO: gh-releases-zsync|MuKonqi|nottodbox|latest|nottodbox-*x86_64.AppImage.zsync
      with:
        recipe: AppImageBuilder.yml

    - name: Create changelog file
      if: startsWith(github.ref, 'refs/tags/')
      run: python3 scripts/changelog.py

    - name: Upload to stable release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.2.1
      with:
        body_path: "CHANGELOG.md"
        files: ./nottodbox*.AppImage*

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: ./nottodbox*.AppImage*
        tag_name: nightly
        prerelease: true