# Credit: While making this file <https://github.com/DavidoTek/ProtonUp-Qt/blob/main/AppImageBuilder.yml> helped me as a reference.

name: Build AppImage

on:
  push:
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: pacman -Sy --noconfirm appstream binutils desktop-file-utils fakeroot gdk-pixbuf2 gettext gtk-update-icon-cache patchelf python python-pip python-pipx python-setuptools squashfs-tools strace wget zsync
    
    - name: Download appimage-builder
      run: pipx install appimage-builder
    
    - name: Build package
      run: /github/home/.local/bin/appimage-builder --recipe .github/scripts/build-appimage.yml

    - name: Upload package
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly"
        files: ./nottodbox*.AppImage*