name: Build AppImage

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  delete-old-nightly-release:
    env:
      GH_TOKEN: ${{ github.token }}
    
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Delete old nightly release
      run: gh release delete nightly --cleanup-tag --yes | true

  build-appimage:
    runs-on: ubuntu-24.04
    container: 
      image: archlinux:latest
      options: --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined

    steps:
    - uses: actions/checkout@v4

    - name: Download dependencies
      run: pacman -Sy --noconfirm fakeroot fuse2 gtk-update-icon-cache python python-pip wget
    
    - name: Download appimage-builder
      run: wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage

    - name: Make executable appimage-builder
      run: chmod +x appimage-builder-x86_64.AppImage

    - name: Prepare the container for appimage-builder
      run: ln -s /usr/lib/libfakeroot/libfakeroot-0.so /usr/lib/libfakeroot/libfakeroot-sysv.so ; ln -s /usr/bin/faked /usr/bin/faked-sysv ; ln -s /usr/bin/fakeroot /usr/bin/fakeroot-sysv
    
    - name: Build AppImage package
      run: ./appimage-builder-x86_64.AppImage --recipe .github/scripts/build-appimage.yml

    - name: Create changelog file
      run: python3 .github/scripts/changelog.py

    - name: Upload to stable release
      uses: softprops/action-gh-release@v2.2.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: "CHANGELOG.md"
        files: ./nottodbox*.AppImage*

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2.2.1
      with:
        body_path: "CHANGELOG.md"
        files: ./nottodbox*.AppImage*
        tag_name: nightly
        prerelease: true