# Credit: While making this file <https://github.com/DavidoTek/ProtonUp-Qt/blob/main/AppImageBuilder.yml> helped me as a reference.

name: Build AppImage

on:
  push:
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Dependencies
      run: pacman -Sy --noconfirm wget
    
    - name: Download AppImage Builder
      run: |
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
    
    - name: Build AppImage
      run: ./appimage-builder-x86_64.AppImage --recipe .github/scripts/build-appimage.yml

    - name: Upload AppImage
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly"
        files: ./nottodbox*.AppImage*