name: Build AppImage

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  setup:
    env:
      GH_TOKEN: ${{ github.token }}
    
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Delete old nightly release
      run: gh release delete nightly --cleanup-tag --yes

  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pacman -Sy --noconfirm appstream binutils desktop-file-utils fakeroot gdk-pixbuf2 gettext gtk-update-icon-cache patchelf python python-pip python-pipx python-setuptools squashfs-tools strace wget zsync
    
    - name: Download appimage-builder
      run: pipx install appimage-builder
    
    - name: Build AppImage package
      run: /github/home/.local/bin/appimage-builder --recipe .github/scripts/build-appimage.yml

    - name: Create changelog file
      run: python3 .github/scripts/changelog.py

    - name: Upload to stable release
      uses: softprops/action-gh-release@v2.2.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: "CHANGELOG.md"
        files: ./nottodbox*.AppImage*

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2.2.1
      with:
        body_path: "CHANGELOG.md"
        files: ./nottodbox*.AppImage*
        tag_name: nightly
        prerelease: true