name: Build

on:
  pull_request:
  push: 
    tags: "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-14', 'windows-2022']

    steps:
    - uses: actions/checkout@v4

    - uses: samypr100/setup-dev-drive@v3
      if: runner.os == 'Windows'
      with:
        workspace-copy: true

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: pip install PySide6-Essentials pyinstaller

    - name: Install libraries (Linux)
      if: runner.os == 'Linux'
      run: sudo apt install -y libfuse2 libgdk-pixbuf2.0-dev libglib2.0-0 libopengl0 libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0-dev libxcb-xkb-dev libxkbcommon-x11-0

    - name: Set-up translations
      run: python3 .github/scripts/translations.py

    - name: Set-up consts
      run: python3 .github/scripts/consts.py --github

    - name: Build executable
      run: bash .github/scripts/pyinstaller.sh

    - name: Build AppImage (Linux)
      if: runner.os == 'Linux'
      run: |
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20250213-2/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage

        mkdir -p AppDir/usr/bin
        mv dist/nottodbox AppDir/usr/bin
        ./linuxdeploy-x86_64.AppImage \
          --appdir AppDir \
          -d share/applications/io.github.mukonqi.nottodbox.desktop \
          -i share/icons/hicolor/256x256/apps/io.github.mukonqi.nottodbox.png \
          -l $(ldconfig -p | grep libglib-2.0.so.0 | awk '{print $NF}' | head -n1) \
          -l $(ldconfig -p | grep libOpenGL.so.0 | awk '{print $NF}' | head -n1) \
          -l $(ldconfig -p | grep libxcb-cursor.so.0 | awk '{print $NF}' | head -n1) \
          --output appimage

    - name: Set-up the file (non-Windows)
      if: runner.os != 'Windows'
      run: python3 .github/scripts/setup.py

    - name: Upload to stable release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        tag_name: nightly
        prerelease: true