name: Build AppImage

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Dependencies
      run: sudo apt install -y appstream desktop-file-utils gettext python3 python3-pip

    - name: Download AppImageBuilder
      run: pip3 install appimage-builder
    
    - name: Build AppImage
      run: appimage-builder

    - name: Upload AppImage
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "appimage"
        prerelease: true
        title: "New AppImage Release"
        files: ./nottodbox*.AppImage*