name: Build AppImage

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Install dependencies
      run: sudo apt install -y appstream desktop-file-utils gettext meson ninja-build python3 python3-pip

    - name: Download AppImageBuilder and PySide6
      run: pip3 install appimage-builder PySide6-Essentials
    
    - name: Build AppImage
      run: appimage-builder

    - name: Upload AppImage
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: ./nottodbox*.AppImage*