name: Build AppImage

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt install -y libfuse2 libglib2.0-0 libopengl0 libxcb-cursor0 libxcb-keysyms1 libxcb-icccm4 libxcb-shape0-dev libxkbcommon-x11-0 libxcb-xkb-dev patchelf wget
        pip install pyinstaller PySide6-Essentials

    - name: Build executable
      run: bash .github/scripts/pyinstaller.sh

    - name: Prepare AppDir
      run: |
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/lib
        mkdir -p AppDir/usr/share/applications/
        mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
        mkdir -p AppDir/usr/share/metainfo

        cp dist/nottodbox AppDir/usr/bin/

        cp share/applications/io.github.mukonqi.nottodbox.desktop AppDir/usr/share/applications/io.github.mukonqi.nottodbox.desktop
        cp share/applications/io.github.mukonqi.nottodbox.desktop AppDir/io.github.mukonqi.nottodbox.desktop

        cp share/icons/hicolor/scalable/apps/io.github.mukonqi.nottodbox.svg AppDir/usr/share/icons/hicolor/scalable/apps/io.github.mukonqi.nottodbox.svg
        cp share/icons/hicolor/scalable/apps/io.github.mukonqi.nottodbox.svg AppDir/io.github.mukonqi.nottodbox.svg

        cp share/metainfo/io.github.mukonqi.nottodbox.appdata.xml AppDir/usr/share/metainfo/io.github.mukonqi.nottodbox.appdata.xml

    - name: Download linuxdeploy + linuxdeploy-plugin-qt
      run: |
        wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        chmod +x linuxdeploy-*.AppImage

    - name: Build AppImage
      run: |
        ./linuxdeploy-x86_64.AppImage --appdir AppDir \
          -d AppDir/usr/share/applications/io.github.mukonqi.nottodbox.desktop \
          -i AppDir/usr/share/icons/hicolor/scalable/apps/io.github.mukonqi.nottodbox.svg \
          --plugin qt

    - name: Rename AppImage
      run: mv Nottodbox-x86_64.AppImage nottodbox.AppImage

    - name: Upload to stable release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.2.1
      with:
        body_path: "CHANGELOG.md"
        files: 'nottodbox.AppImage'

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: 'nottodbox.AppImage'
        tag_name: nightly
        prerelease: true