# Credit: While making this file <https://github.com/DavidoTek/ProtonUp-Qt/blob/main/AppImageBuilder.yml> helped me as a reference.

name: Build AppImage

on:
  push:
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v1

    - name: Set environment for appimage-builder
      run: |
        pacman -Sy --noconfirm fuse2 python wget
        ln -s /usr/lib/libfakeroot/libfakeroot-0.so /usr/lib/libfakeroot/libfakeroot-sysv.so
        ln -s /usr/bin/faked /usr/bin/faked-sysv
        ln -s /usr/bin/fakeroot /usr/binfakeroot-sysv
    
    - name: Download appimage-builder
      run: |
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
    
    - name: Build package
      run: ./appimage-builder-x86_64.AppImage --appimage-extract-and-run --recipe .github/scripts/build-appimage.yml

    - name: Upload package
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly"
        files: ./nottodbox*.AppImage*