name: Build Executable via PyInstaller

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  build-executable-via-pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'macos-15', 'windows-2025']

    steps:
    - uses: actions/checkout@v4

    - uses: samypr100/setup-dev-drive@v3
      if: runner.os == 'Windows'
      with:
        workspace-copy: true

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: pip install Pillow PySide6-Essentials pyinstaller

    - name: Build executable
      run: bash .github/scripts/pyinstaller.sh

    - name: Rename executable file for macOS
      if: runner.os == 'macOS'
      run: mv dist/nottodbox dist/nottodbox-mac

    - name: Upload to stable release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.2.1
      with:
        body_path: "CHANGELOG.md"
        files: dist/*

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: dist/*
        tag_name: nightly
        prerelease: true