name: Build AppImage

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  delete-old-nightly-release:
    env:
      GH_TOKEN: ${{ github.token }}
    
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Delete old nightly release
      run: gh release delete nightly --cleanup-tag --yes | true

  build-appimage:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Download dependencies
      run: apt install -y binutils coreutils desktop-file-utils fakeroot fuse gettext libgdk-pixbuf2.0-dev patchelf pipx python3-pip python3-setuptools squashfs-tools strace util-linux zsync
    
    - name: Download appimage-builder
      run: pipx install appimage-builder

    - name: Run appimage-builder
      run: appimage-builder

    - name: Create changelog file
      if: startsWith(github.ref, 'refs/tags/')
      run: python3 scripts/changelog.py

    - name: Upload to stable release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2.2.1
      with:
        body_path: "CHANGELOG.md"
        files: ./nottodbox*.AppImage*

    - name: Upload to nightly release
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: ./nottodbox*.AppImage*
        tag_name: nightly
        prerelease: true