name: Lint (via Ruff)

on:
  pull_request:
  push: 
    tags: "v*.*.*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: astral-sh/ruff-action@v3
      - run: ruff check . --fix