name: Ruff

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 

      - name: Set-up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Format
        id: ruff_format_step
        run: |
          echo "Running ruff format..."
          ruff format .

          if git diff --exit-code; then
            echo "No formatting changes detected."
            echo "has_format_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Formatting changes detected."
            echo "has_format_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Format Fixes
        if: steps.ruff_format_step.outputs.has_format_changes == 'true' && github.event.pull_request.draft == false
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "style: Format code (via Ruff)"
          git push

      - name: Run Ruff Check and Fix
        id: ruff_check_step
        run: |
          echo "Running ruff check --fix..."
          ruff check . --fix

          if git diff --exit-code; then
            echo "No linting changes detected."
            echo "has_lint_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Linting changes detected."
            echo "has_lint_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Lint Fixes
        if: steps.ruff_check_step.outputs.has_lint_changes == 'true' && github.event.pull_request.draft == false
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "fix: Apply linting fixes (via Ruff)"
          git push