name: Set-up release

on:
  pull_request:
  push: 
    tags: "*"
  workflow_dispatch:

jobs:
  set-up-release:
    env:
      GH_TOKEN: ${{ github.token }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Delete old nightly release
      run: gh release delete nightly --cleanup-tag --yes | true

    - name: Create changelog file
      if: startsWith(github.ref, 'refs/tags/')
      run: python3 .github/scripts/changelog.py

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        body_path: "CHANGELOG.md"